#!/bin/sh

SCRIPT=$(readlink -f $0)
SCRIPTPATH=$(dirname $SCRIPT)
JAR=$SCRIPTPATH/../target/neverland.jar
JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Xmx1G"

whitespace="[[:space:]]"
C="java $JAVA_OPTS -cp $JAR nl.cwi.da.neverland.daemons.Worker"

for i in "$@";do 
    C="$C \"${i//\"/\\\"}\""
done;

if echo "$C" | grep --quiet "%hostname%" ; then
	hn=`hostname`
  	C=`echo "$C" | sed "s/%hostname%/$hn/"`
fi

sh -c "$C"
